msaconfig
  greeting: "hello"

---

spring:
  profiles: stage

msaconfig:
  greeting: "welcome to staging server"

---

spring:
  profiles: dev
  
msaconfig:
  greeting: "welcome to dev server"

---

spring:
  profiles: local
  
msaconfig:
  greeting: "welcome to local"

