msaconfig:
  greeting: "hello"
  
---

spring:
  profiles: local

msaconfig:
  greeting: "welcome to local pilot server"

---

spring:
  profiles: dev

msaconfig:
  greeting: "welcome to dev pilot server"

---

spring:
  profiles: test
  
msaconfig:
  greeting: "welcome to test mvp server"

---

spring:
  profiles: staging
  
msaconfig:
  greeting: "welcome to staging v1 server"

---

spring:
  profiles: prod
  
msaconfig:
  greeting: "welcome to prod v1 server"
