spring:
  profiles: pilot

msaconfig:
  greeting: "welcome to local pilot server"

---

spring:
  profiles: mvp
  
msaconfig:
  greeting: "welcome to local mvp server"

---

spring:
  profiles: v1
  
msaconfig:
  greeting: "welcome to local mvp server"

---
